/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
static yyconst short int yy_acclist[411] =
    {   0,
       71,   69,   70,   59,   69,   70,   59,   70,   52,   69,
       70,   69,   70,   56,   69,   70,   53,   69,   70,   52,
       69,   70,   69,   70,   51,   69,   70,   52,   69,   70,
       52,   69,   70,   56,   69,   70,   52,   69,   70,   51,
       69,   70,   53,   69,   70,   42,   69,   70,   43,   69,
       70,   54,   69,   70,   50,   54,   69,   70,   53,   69,
       70,   55,   69,   70,   53,   69,   70,   54,   69,   70,
       58,   69,   70,   58,   69,   70,   69,   70,   53,   69,
       70,   58,   69,   70,   58,   69,   70,   58,   69,   70,
       58,   69,   70,   58,   69,   70,   58,   69,   70,   58,

       69,   70,   58,   69,   70,   58,   69,   70,   58,   69,
       70,   58,   69,   70,   58,   69,   70,   58,   69,   70,
       58,   69,   70,   58,   69,   70,   58,   69,   70,   50,
       51,   69,   70,   53,   69,   70,   52,   69,   70,   56,
       69,   70,    3,   70,    3,   70,    3,   70,   67,   68,
       70,   68,   70,   59,   53,   49,   56,   57,   55,   57,
       52,   51,   45,    1,   45,   42,   42,   42,   42,   43,
       43,   43,   43,   50,   53,   53,   58,   60,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   33,   58,   58,
       58,   58,   58,   58,   58,   37,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,    3,    3,
        2,   67,   48,   54,   45,    4,   46,   42,   42,   42,
       42,   44,   43,   43,   43,   43,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       35,   58,   58,   58,   16,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   61,   45,   46,   42,   44,   44,   44,   43,
       58,   58,   58,    8,   58,   58,   30,   58,    9,   58,
       58,   58,   58,   58,   34,   58,   12,   58,   58,   58,
       36,   58,   58,   17,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   27,   58,   58,
       58,   44,   44,   47,   44,   44,    5,   58,   58,   58,
       29,   58,   10,   58,   58,   58,   58,   58,   14,   58,
       58,   58,   58,   58,   20,   58,   58,   58,   58,   58,
       58,   58,   25,   58,   58,   58,   41,   58,   62,   65,
       47,   44,   58,   58,   58,   58,   58,   11,   58,   13,
       58,   15,   58,   58,   58,   38,   58,   21,   58,   39,
       58,   22,   58,   23,   58,   40,   58,   58,   58,   58,
       63,   58,   58,   58,   32,   58,   58,   58,   24,   58,
       58,   58,   64,    6,   58,   58,   31,   58,   18,   58,

       19,   58,   26,   58,   28,   58,   58,   66,    7,   58
    } ;

static yyconst short int yy_accept[403] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   14,   17,   20,   23,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   59,   62,   65,
       68,   71,   74,   77,   79,   82,   85,   88,   91,   94,
       97,  100,  103,  106,  109,  112,  115,  118,  121,  124,
      127,  130,  134,  137,  140,  143,  145,  147,  149,  152,
      154,  155,  156,  156,  157,  157,  157,  158,  158,  158,
      158,  158,  159,  160,  161,  161,  161,  162,  163,  163,
      164,  165,  165,  166,  167,  167,  167,  168,  169,  169,
      170,  171,  172,  173,  174,  175,  176,  177,  178,  178,

      178,  179,  179,  179,  180,  181,  182,  183,  184,  185,
      186,  187,  188,  190,  191,  192,  193,  194,  195,  196,
      198,  199,  200,  201,  202,  203,  204,  205,  206,  207,
      208,  209,  209,  209,  209,  210,  211,  212,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  214,
      214,  214,  214,  214,  215,  215,  216,  216,  217,  217,
      218,  219,  220,  221,  222,  222,  223,  224,  225,  226,
      227,  227,  227,  227,  227,  228,  229,  230,  231,  232,
      233,  234,  235,  236,  237,  238,  239,  240,  241,  243,
      244,  245,  247,  248,  249,  250,  251,  252,  253,  254,

      255,  256,  257,  258,  259,  260,  261,  262,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  264,
      264,  264,  264,  264,  264,  264,  265,  266,  267,  267,
      267,  268,  268,  269,  270,  271,  271,  271,  271,  271,
      272,  273,  274,  276,  277,  279,  281,  282,  283,  284,
      285,  287,  289,  290,  291,  293,  294,  296,  297,  298,
      299,  300,  301,  302,  303,  304,  305,  306,  307,  308,
      310,  311,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  313,  314,  314,  315,
      316,  317,  317,  317,  317,  317,  319,  320,  321,  323,

      325,  326,  327,  328,  329,  331,  332,  333,  334,  335,
      337,  338,  339,  340,  341,  342,  343,  345,  346,  347,
      349,  349,  349,  349,  349,  349,  350,  350,  350,  351,
      351,  351,  352,  353,  353,  353,  353,  354,  355,  356,
      357,  358,  360,  362,  364,  365,  366,  368,  370,  372,
      374,  376,  378,  379,  380,  381,  381,  381,  381,  381,
      381,  382,  382,  382,  382,  382,  383,  384,  385,  387,
      388,  389,  391,  392,  393,  393,  393,  393,  394,  394,
      394,  394,  396,  397,  399,  401,  403,  405,  407,  407,
      407,  407,  407,  407,  408,  408,  409,  409,  409,  409,

      411,  411
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   36,
       33,   33,   33,   33,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    4,    1,    1,    1,    5,    1,    6,    6,
        7,    1,    1,    1,    1,    8,    9,    7,    7,    7,
        7,    7,   10,   10,   10,   10,   11,   11,    1,   11,
        1,    1,   10,    6,    6,    7,    7,    7,    6,   10,
       10,   10,   10,   10,   10,   11,   10,   10,   11,   10,
       11,   11,   11,   10,   11,   10,   10,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[465] =
    {   0,
        0, 1007,   69,   70,   68,   69, 1013, 1015,   74,   77,
      987,   78,   81,   64,   78,  971, 1015,  985,   77, 1015,
       80,   80,   91,  119,  124,  983, 1015,   90,  983,   67,
     1015,  967,  102,  114,  981,   90,   70,   67,  109,  122,
      129,  123,   91,  142,  107,   73,  148,   71,  112,  118,
       83, 1015,  102, 1015,  185, 1002, 1001,  985,    0, 1015,
      193, 1015,  168, 1015,  182,  201, 1015,  954,  150,  952,
      948,  991, 1015, 1015,  183,  197, 1015, 1015,  981,  237,
     1015,  994,  244,  280,  194,  208,  208,  111,  979,  184,
      285,  215,  172,  234, 1015,  970,  969,  953,  199,  234,

     1015,    0,    0,  226,  227,  163,  170,  233,  220,  238,
      247,  269,  250,  254,  267,  190,  268,  273,  249,  952,
      283,  279,  290,  281,  286,  287,  303,  301,  305,  308,
      309,  350,  362,  307,  988,  987, 1015,    0,  352,    0,
        0,    0,  940,  928,  940,  983,  929,  962, 1015,  357,
        0,    0,    0, 1015,  354, 1015,  980, 1015,  359,  363,
      332, 1015,  947,  927,    0,  364,  349, 1015,  945,  925,
        0,    0,    0,    0,  347,  348,  345,  350,  375,  365,
      366,  368,  380,  351,  383,  381,  387,  390,  938,  392,
      393,  937,  397,  398,  399,  400,  402,  401,  403,  404,

      406,  408,  415,  413,  412,  419,  414,  427,  920,  929,
      465,    0,  500,    0,  922,  925,  920,  968, 1015,  922,
      463,    0,  540,    0,  455,  458, 1015, 1015,  436,  444,
      451,  495,  454,  463, 1015,    0,    0,    0,    0,  447,
      452,  483,  929,  201,  928,  927,  457,  482,  464,  484,
      926,  925,  495,  496,  924,  487,  923,  502,  497,  499,
      512,  451,  524,  501,  536,  537,  527,  523,  515,  922,
      535,  550,  907,  560,    0,    0,    0,  904,  956,  909,
      790,  568,    0,    0,    0,  554, 1015,  573,  582,  756,
      736,    0,    0,    0,    0,  748,  555,  559,  747,  743,

      557,  564,  567,  565,  741,  572,  566,  570,  579,  740,
      583,  584,  586,  585,  588,  589,  738,  594,  600,  737,
      709,    0,    0,  717,  753, 1015,  747,  746, 1015,    0,
        0, 1015, 1015,    0,    0,    0,  698,  601,  598,  602,
      604,  661,  660,  658,  603,  607,  657,  655,  654,  653,
      652,  647,  608,  615,  605,  636,    0,  650,  678,  672,
     1015,    0,  648,    0,    0,  620,  622,  621,  511,  627,
      628,  458,  630,  631,  448,    0,  492, 1015,    0,    0,
        0,  416,  632,  353,  284,  255,  150,   85,  672,    0,
        0,    0,    0,  633,  678, 1015,    0,    0,    0,   82,

     1015,  702,  713,  724,  735,  741,  752,  763,  773,  783,
      794,  801,  803,  805,  807,  809,  811,  818,  824,  826,
      828,  830,  832,  834,  836,  838,  840,  842,  844,  846,
      848,  850,  852,  854,  856,  858,  865,  876,  882,  884,
      886,  888,  890,  892,  894,  896,  903,  909,  911,  913,
      915,  917,  919,  926,  932,  934,  936,  938,  940,  942,
      944,  946,  948,  950
    } ;

static yyconst short int yy_def[465] =
    {   0,
      401,    1,  402,  402,  403,  403,  401,  401,  401,  401,
      401,  404,  401,  401,  401,  405,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  406,  406,  401,  401,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  401,  401,  401,  401,  407,  407,  401,  408,  401,
      401,  401,  404,  401,  409,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  405,  410,  401,  401,  401,  401,
      401,  411,  401,  401,  401,  401,  401,  401,  412,  401,
      401,  401,  401,  401,  401,  401,  401,  406,  401,  404,

      401,  413,  414,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  401,  401,  401,  407,  407,  401,  408,  404,  415,
      416,  417,  401,  401,  401,  418,  401,  401,  401,  405,
      419,  420,  421,  401,  401,  401,  411,  401,  401,  401,
      401,  401,  401,  401,  422,  412,  401,  401,  401,  401,
      423,  424,  425,  426,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  401,  401,
      404,  427,  404,  428,  401,  401,  401,  418,  401,  401,
      405,  429,  405,  430,  401,  401,  401,  401,  422,  422,
      401,  401,  401,  401,  401,  431,  432,  433,  434,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  401,  404,  435,  213,  436,  401,  437,  401,
      438,  405,  439,  223,  440,  401,  401,  401,  401,  401,
      401,  441,  442,  443,  444,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      401,  445,  446,  401,  437,  401,  447,  438,  401,  448,
      449,  401,  401,  450,  451,  452,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  401,  453,  404,  454,  447,
      401,  455,  405,  456,  457,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  401,  458,  454,  401,  459,  460,
      461,  406,  406,  406,  406,  406,  406,  406,  401,  462,
      463,  464,  444,  406,  401,  401,  446,  449,  451,  406,

        0,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401
    } ;

static yyconst short int yy_nxt[1087] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   32,
       32,   32,   32,   32,   33,   32,   32,   32,   17,   34,
       17,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       32,   44,   32,   45,   32,   32,   32,   32,   46,   47,
       48,   49,   50,   51,   32,   32,   32,   52,   53,   17,
       54,   57,   57,   60,   60,   61,   61,   61,   61,   61,
       61,   58,   58,   64,   66,   72,   62,   67,   73,   74,
       77,   62,   97,   60,   60,   77,   79,   95,   80,   80,

       80,   73,   73,   81,   73,   78,   99,  100,   82,   99,
       99,   74,   99,   96,   62,   73,  101,   65,  104,  105,
      123,   99,   99,  106,   99,  108,   73,   68,   69,   99,
       99,  107,   70,  131,   71,   83,  128,   84,   84,   85,
       83,   99,   91,   91,   91,  163,   99,  119,   99,   86,
      102,   99,  109,   87,   86,   88,   89,   99,   92,  110,
       93,   99,   99,  122,  164,  111,   86,  129,   99,  112,
       62,   86,   90,   64,  130,  103,  117,   94,  113,  118,
       88,   99,  114,   89,  115,   93,  132,   99,  133,   99,
      120,   67,  149,  116,   61,   61,   61,  121,  124,  125,

      139,  139,   99,  144,   66,  145,  169,   65,  126,   99,
       83,  127,   85,   85,   85,  150,  150,  177,  140,  141,
      162,  159,   76,  159,   86,  170,  160,  160,  160,   99,
      178,   68,   69,  151,  152,  171,  134,  161,   71,   64,
       99,   86,  161,  142,  162,  162,  141,   68,   69,  167,
      187,  168,   70,  299,   71,   80,   80,   80,  153,   99,
      172,  152,   80,   80,   80,   99,   99,  155,  156,  162,
      168,  156,   99,   65,  155,  156,  168,   99,  156,  180,
      179,  181,  175,  176,  155,  156,   99,  167,   99,   99,
      156,  155,  156,   99,   99,  168,   83,  156,   84,   84,

       85,   83,  182,   91,   91,   91,   99,   99,   99,  190,
       86,  184,   99,  185,   87,   86,   88,  183,   99,   92,
       99,   93,   99,   99,  188,   99,   99,   86,  186,   99,
      200,  189,   86,   90,  193,  198,  191,  197,   94,  194,
       99,   88,   99,  192,   99,  201,   93,   99,   99,  195,
      196,  132,  199,  132,  202,  146,  204,   64,  203,  206,
      208,  207,  210,  132,  205,  133,  149,  225,  162,  225,
      211,  211,  226,  226,  226,  221,  221,  160,  160,  160,
      230,  160,  160,  160,   99,  168,   99,   99,  242,   99,
       99,   65,   99,  162,  227,  250,   76,  227,  231,  232,

      233,  209,  241,  240,   99,   99,  243,   99,   68,   69,
      168,  227,  245,  134,   99,   71,  227,  234,  244,   99,
       99,  232,   99,  249,  246,  233,   99,  247,  248,   99,
      251,   99,   99,  254,  253,  252,   99,   99,   99,   99,
       99,   99,   99,   99,  256,   99,  257,   99,  255,  258,
      263,   99,   99,   99,   99,   99,  262,  271,   99,  259,
      261,  260,  267,  269,  264,  270,   99,  265,  266,  268,
       64,  232,  149,  226,  226,  226,  226,  226,  226,  232,
      272,  282,  282,  274,  274,  286,   99,  287,  290,  156,
       99,   99,  156,  232,  378,  389,   99,   99,  311,  287,

      296,  232,   76,   99,   65,   64,  156,  291,  288,  297,
      288,  156,  287,  289,  289,  289,  286,  300,  276,  276,
      276,   99,   99,   99,  287,  302,   99,  276,  276,  276,
      276,  276,  298,  301,   99,   99,   99,  303,   99,   65,
       99,   99,  306,  276,  276,  276,  276,  276,  276,  149,
       99,   99,  313,  304,   99,  308,  305,  309,  284,  284,
      284,  307,   99,   99,  318,   64,   99,  284,  284,  284,
      284,  284,  310,  316,   99,   99,   99,  149,  317,   76,
      312,  314,  315,  284,  284,  284,  284,  284,  284,   99,
      287,  289,  289,  289,   99,  319,   99,  320,   99,   65,

      289,  289,  289,   99,   99,   99,   99,   76,  338,   99,
      339,   99,  340,  332,  342,  287,  332,  341,   99,  344,
      343,  346,   99,   99,   99,   99,  345,   99,   99,  348,
      332,  350,  349,   99,  347,  332,  353,   99,  352,   99,
       99,   99,   99,   99,   99,  351,   99,   99,  366,  354,
      370,  355,  371,  367,   99,   64,  372,  149,  374,   99,
       99,   99,  373,  368,  369,  383,   99,   99,  384,   99,
       99,   99,   99,  395,  361,  395,  387,  396,  388,  395,
      378,  395,  375,  396,  382,  385,   99,   76,  386,   65,
      394,   99,   99,   99,   99,  396,   99,   99,  400,   99,

       99,  396,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   75,   75,   99,   75,   75,
       75,   75,   75,   75,   75,   75,   98,   98,  329,  361,
       98,   98,  135,  135,  135,  326,  135,  135,  135,  135,
      135,  135,  135,  138,  359,  138,  138,  138,  138,  138,
      356,  138,  138,  138,   63,   63,   99,   99,   63,   99,
       99,   63,   99,   63,   75,   75,   99,   99,   75,  333,
      333,   75,  329,   75,  157,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  157,  166,  166,  166,  173,  173,
      174,  174,  212,  212,  213,  213,  214,  214,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  222,
      222,  223,  223,  224,  224,  229,  229,  236,  236,  237,
      237,  238,  238,  239,  239,  275,  275,  277,  277,  283,
      283,  285,  285,  292,  292,  293,  293,  294,  294,  295,
      295,  322,  322,  323,  323,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  330,  330,  331,
      331,  334,  334,  335,  335,  336,  336,  337,  337,  357,

      357,  358,  358,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  362,  362,  363,  363,  364,  364,
       98,   98,  365,  365,  376,  376,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  379,  379,  380,
      380,  381,  381,  390,  390,  391,  391,  392,  392,  393,
      393,  397,  397,  398,  398,  399,  399,  327,  326,  324,
      321,   99,   99,   99,   99,   99,   99,   99,   99,  281,
      219,  280,  279,  278,  273,  210,   99,   99,  235,  235,
      228,  228,  158,   74,  220,  219,  217,  216,  215,  136,
      136,   99,   99,   73,   73,  165,  158,  154,  148,  147,

      146,  143,  137,  136,  136,   73,   99,   62,   74,   73,
       76,   62,  401,   55,    7,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401
    } ;

static yyconst short int yy_chk[1087] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    9,    9,    9,   10,   10,
       10,    3,    4,   12,   13,   14,   15,   13,   14,   14,
       19,   30,   30,    5,    6,   21,   22,   28,   22,   22,

       22,   19,   15,   23,   21,   21,   38,   33,   23,   37,
       48,   28,   46,   28,   28,   23,   34,   12,   36,   36,
       46,  400,   51,   36,  388,   38,   53,   13,   13,   36,
       43,   37,   13,   51,   13,   24,   48,   24,   24,   24,
       25,   33,   25,   25,   25,   88,   45,   43,   39,   24,
       34,   49,   39,   24,   25,   24,   24,   50,   25,   39,
       25,   40,   42,   45,   88,   39,   24,   49,   41,   40,
       53,   25,   24,   63,   50,   34,   42,   25,   40,   42,
       24,   44,   41,   24,   41,   25,   55,   47,   55,  387,
       44,   55,   75,   41,   61,   61,   61,   44,   47,   47,

       65,   65,  106,   69,   66,   69,   93,   63,   47,  107,
       85,   47,   85,   85,   85,   76,   76,  106,   65,   65,
       90,   86,   75,   86,   85,   93,   86,   86,   86,  116,
      107,   55,   55,   76,   76,   99,   55,   90,   55,  100,
      244,   85,   87,   65,   87,   90,   65,   66,   66,   92,
      116,   92,   66,  244,   66,   80,   80,   80,   76,  109,
       99,   76,   83,   83,   83,  104,  105,   80,   80,   87,
       94,   80,  108,  100,   83,   83,   92,  110,   83,  109,
      108,  110,  104,  105,   80,   80,  111,   94,  119,  113,
       80,   83,   83,  114,  386,   94,   84,   83,   84,   84,

       84,   91,  111,   91,   91,   91,  115,  117,  112,  119,
       84,  113,  118,  114,   84,   91,   84,  112,  122,   91,
      124,   91,  121,  385,  117,  125,  126,   84,  115,  123,
      126,  118,   91,   84,  122,  125,  121,  124,   91,  123,
      128,   84,  127,  121,  129,  126,   91,  130,  131,  123,
      123,  132,  125,  132,  127,  134,  129,  139,  128,  130,
      131,  130,  134,  133,  129,  133,  150,  155,  161,  155,
      139,  139,  155,  155,  155,  150,  150,  159,  159,  159,
      166,  160,  160,  160,  177,  167,  175,  176,  177,  178,
      184,  139,  384,  161,  160,  184,  150,  160,  166,  166,

      166,  132,  176,  175,  180,  181,  178,  182,  133,  133,
      167,  160,  180,  133,  179,  133,  160,  166,  179,  183,
      186,  166,  185,  183,  181,  166,  187,  182,  182,  188,
      185,  190,  191,  188,  187,  186,  193,  194,  195,  196,
      198,  197,  199,  200,  191,  201,  193,  202,  190,  194,
      199,  205,  204,  207,  203,  382,  198,  207,  206,  195,
      197,  196,  203,  205,  200,  206,  208,  201,  202,  204,
      211,  229,  221,  225,  225,  225,  226,  226,  226,  230,
      208,  221,  221,  211,  211,  231,  240,  231,  233,  226,
      262,  241,  226,  229,  377,  375,  247,  372,  262,  234,

      240,  230,  221,  249,  211,  213,  226,  233,  232,  241,
      232,  226,  231,  232,  232,  232,  234,  247,  213,  213,
      213,  248,  242,  250,  234,  249,  256,  213,  213,  213,
      213,  213,  242,  248,  253,  254,  259,  250,  260,  213,
      264,  258,  256,  213,  213,  213,  213,  213,  213,  223,
      369,  261,  264,  253,  269,  259,  254,  260,  223,  223,
      223,  258,  268,  263,  269,  274,  267,  223,  223,  223,
      223,  223,  261,  267,  271,  265,  266,  282,  268,  223,
      263,  265,  266,  223,  223,  223,  223,  223,  223,  272,
      286,  288,  288,  288,  297,  271,  301,  272,  298,  274,

      289,  289,  289,  302,  304,  307,  303,  282,  297,  308,
      298,  306,  301,  289,  303,  286,  289,  302,  309,  306,
      304,  308,  311,  312,  314,  313,  307,  315,  316,  311,
      289,  313,  312,  318,  309,  289,  316,  339,  315,  319,
      338,  340,  345,  341,  355,  314,  346,  353,  338,  318,
      345,  319,  346,  339,  354,  358,  353,  363,  355,  366,
      368,  367,  354,  340,  341,  367,  370,  371,  368,  373,
      374,  383,  394,  389,  360,  389,  373,  389,  374,  395,
      359,  395,  356,  395,  366,  370,  352,  363,  371,  358,
      383,  351,  350,  349,  348,  389,  347,  344,  394,  343,

      342,  395,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  405,  405,  337,  405,  405,
      405,  405,  405,  405,  405,  405,  406,  406,  328,  327,
      406,  406,  407,  407,  407,  325,  407,  407,  407,  407,
      407,  407,  407,  408,  324,  408,  408,  408,  408,  408,
      321,  408,  408,  408,  409,  409,  320,  317,  409,  310,
      305,  409,  300,  409,  410,  410,  299,  296,  410,  291,
      290,  410,  281,  410,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  412,  412,  412,  413,  413,
      414,  414,  415,  415,  416,  416,  417,  417,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  419,
      419,  420,  420,  421,  421,  422,  422,  423,  423,  424,
      424,  425,  425,  426,  426,  427,  427,  428,  428,  429,
      429,  430,  430,  431,  431,  432,  432,  433,  433,  434,
      434,  435,  435,  436,  436,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  439,  439,  440,
      440,  441,  441,  442,  442,  443,  443,  444,  444,  445,

      445,  446,  446,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  448,  448,  449,  449,  450,  450,
      451,  451,  452,  452,  453,  453,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  455,  455,  456,
      456,  457,  457,  458,  458,  459,  459,  460,  460,  461,
      461,  462,  462,  463,  463,  464,  464,  280,  279,  278,
      273,  270,  257,  255,  252,  251,  246,  245,  243,  220,
      218,  217,  216,  215,  210,  209,  192,  189,  170,  169,
      164,  163,  157,  148,  147,  146,  145,  144,  143,  136,
      135,  120,   98,   97,   96,   89,   82,   79,   72,   71,

       70,   68,   58,   57,   56,   35,   32,   29,   26,   18,
       16,   11,    7,    2,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fb2-5.l"
#define INITIAL 0
/* fb2-5 C cross-ref */
#define COMMENT 1

#define IFILE 2

#line 11 "fb2-5.l"
struct symbol {
	struct ref *reflist;
	char *name;
};

struct ref {
	struct ref *next;
	char *filename;
	int flags;
	int lineno;
};

#define NHASH 9997
struct symbol symtab[NHASH];


/* hash a symbol */
static unsigned symhash(char *sym)
{
	unsigned int hash = 0;
	unsigned c;
	
	while(c = *sym++) hash = hash*9 ^ c;
	
	return hash;
}

struct symbol *lookup(char* sym)
{
	struct symbol *sp = &symtab[symhash(sym)%NHASH];
	int scount = NHASH;

	while(--scount >= 0) {
		if(sp->name && !strcasecmp(sp->name, sym)) return sp;
		if(!sp->name) {
			sp->name = strdup(sym);
			sp->reflist = 0;
			return sp;
		}
		if(++sp >= symtab+NHASH) sp = symtab; /* try the next entry */
	}
	fputs("symbol table overflow\n", stderr);
	abort(); /* tried them all, table is full */
}
void addref(int lineno, char *filename, char *word, int flags)
{
	struct ref *r;
	struct symbol *sp = lookup(word);
	if(sp->reflist &&
	sp->reflist->lineno == lineno &&
	sp->reflist->filename == filename) return;

	r = malloc(sizeof(struct ref));
	if(!r) {fputs("out of space\n", stderr); abort(); }
	r->next = sp->reflist;
	r->filename = filename;
	r->lineno = lineno;
	r->flags = flags;
	sp->reflist = r;
}

char *curfilename;

struct bufstack {
	struct bufstack *prev;
	YY_BUFFER_STATE bs;
	int lineno;
	char *filename;
	FILE *f;
} *curbs;

int
	newfile(char *fn)
{
	FILE *f = fopen(fn, "r");
	struct bufstack *bs = malloc(sizeof(struct bufstack));
		/* die if no file or no room */
	if(!f) { perror(fn); return 0; }
	if(!bs) { perror("malloc"); exit(1); }
		/* remember state */
	if(curbs)curbs->lineno = yylineno;
	bs->prev = curbs;
		/* set up current entry */
	bs->bs = yy_create_buffer(f, YY_BUF_SIZE);
		bs->f = f;
	bs->filename = strdup(fn);
	yy_switch_to_buffer(bs->bs);
	curbs = bs;
	yylineno = 1;
	curfilename = bs->filename;
	return 1;
}
int
	popfile(void)
{
	struct bufstack *bs = curbs;
	struct bufstack *prevbs;
	if(!bs) return 0;
	
	/* get rid of current entry */
	fclose(bs->f);
	free(bs->f);
	yy_delete_buffer(bs->bs);
	
	/* switch back to previous */
	prevbs = bs->prev;
	free(bs);
	if(!prevbs) return 0;
	
	yy_switch_to_buffer(prevbs->bs);
	curbs = prevbs;
	yylineno = curbs->lineno;
	curfilename = curbs->filename;
	return 1;
}

int defining;
#line 935 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 130 "fb2-5.l"

#line 1102 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 402 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1015 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 131 "fb2-5.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 132 "fb2-5.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 133 "fb2-5.l"

	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 134 "fb2-5.l"
{ printf("%s:%d: Unterminated comment\n", curfilename, yylineno); return 0; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 135 "fb2-5.l"

	YY_BREAK
/* declaration keywords */
case 5:
#line 139 "fb2-5.l"
case 6:
#line 140 "fb2-5.l"
case 7:
#line 141 "fb2-5.l"
case 8:
#line 142 "fb2-5.l"
case 9:
#line 143 "fb2-5.l"
case 10:
#line 144 "fb2-5.l"
case 11:
#line 145 "fb2-5.l"
case 12:
#line 146 "fb2-5.l"
case 13:
#line 147 "fb2-5.l"
case 14:
#line 148 "fb2-5.l"
case 15:
#line 149 "fb2-5.l"
case 16:
#line 150 "fb2-5.l"
case 17:
#line 151 "fb2-5.l"
case 18:
#line 152 "fb2-5.l"
case 19:
#line 153 "fb2-5.l"
case 20:
#line 154 "fb2-5.l"
case 21:
#line 155 "fb2-5.l"
case 22:
#line 156 "fb2-5.l"
case 23:
#line 157 "fb2-5.l"
case 24:
#line 158 "fb2-5.l"
case 25:
#line 159 "fb2-5.l"
case 26:
#line 160 "fb2-5.l"
case 27:
#line 161 "fb2-5.l"
case 28:
YY_RULE_SETUP
#line 161 "fb2-5.l"
{ defining = 1; }
	YY_BREAK
/* keywords */
case 29:
YY_RULE_SETUP
#line 164 "fb2-5.l"

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 165 "fb2-5.l"

	YY_BREAK
case 31:
YY_RULE_SETUP
#line 166 "fb2-5.l"

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 167 "fb2-5.l"

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 168 "fb2-5.l"

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 169 "fb2-5.l"

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 170 "fb2-5.l"

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 171 "fb2-5.l"

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 172 "fb2-5.l"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 173 "fb2-5.l"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 174 "fb2-5.l"

	YY_BREAK
case 40:
YY_RULE_SETUP
#line 175 "fb2-5.l"

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 176 "fb2-5.l"

	YY_BREAK
/* constants */
/* integers */
case 42:
YY_RULE_SETUP
#line 181 "fb2-5.l"

	YY_BREAK
case 43:
YY_RULE_SETUP
#line 182 "fb2-5.l"

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 183 "fb2-5.l"

	YY_BREAK
/* decimal float */
case 45:
YY_RULE_SETUP
#line 186 "fb2-5.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 187 "fb2-5.l"

	YY_BREAK
/* hex float */
case 47:
YY_RULE_SETUP
#line 190 "fb2-5.l"

	YY_BREAK
/* char const */
case 48:
YY_RULE_SETUP
#line 193 "fb2-5.l"

	YY_BREAK
/* string literal */
case 49:
YY_RULE_SETUP
#line 196 "fb2-5.l"

	YY_BREAK
/* punctuators */
case 50:
YY_RULE_SETUP
#line 199 "fb2-5.l"
{ defining = 0; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 200 "fb2-5.l"

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 201 "fb2-5.l"

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 202 "fb2-5.l"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 203 "fb2-5.l"

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 204 "fb2-5.l"

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 205 "fb2-5.l"

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 206 "fb2-5.l"

	YY_BREAK
/* identifier */
case 58:
YY_RULE_SETUP
#line 209 "fb2-5.l"
{addref(yylineno, curfilename, yytext, defining); }
	YY_BREAK
/* whitespace */
case 59:
YY_RULE_SETUP
#line 212 "fb2-5.l"

	YY_BREAK
/* continued line */
case 60:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 215 "fb2-5.l"

	YY_BREAK
/* some preprocessor stuff */
case 61:
YY_RULE_SETUP
#line 218 "fb2-5.l"

	YY_BREAK
case 62:
YY_RULE_SETUP
#line 219 "fb2-5.l"

	YY_BREAK
case 63:
YY_RULE_SETUP
#line 220 "fb2-5.l"

	YY_BREAK
case 64:
YY_RULE_SETUP
#line 221 "fb2-5.l"

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 222 "fb2-5.l"

	YY_BREAK
/* recognize an include */
case 66:
YY_RULE_SETUP
#line 225 "fb2-5.l"
{ BEGIN IFILE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 226 "fb2-5.l"
{
	{ int c;
		while((c = input()) && c != '\n') ;
	}
	newfile(strdup(yytext));
	BEGIN INITIAL;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 234 "fb2-5.l"
{ fprintf(stderr, "%s:%d bad include line\n", curfilename, yylineno);
		BEGIN INITIAL;
		}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 238 "fb2-5.l"
{ if(!popfile()) yyterminate(); }
	YY_BREAK
/* invalid character */
case 69:
YY_RULE_SETUP
#line 241 "fb2-5.l"
{ printf("%s:%d: Mystery character '%s'\n", curfilename, yylineno, yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 242 "fb2-5.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1510 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 402 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 402 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 401);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 242 "fb2-5.l"


/* aux function for sorting */
static int symcompare(const void *xa, const void *xb)
{
	const struct symbol *a = xa;
	const struct symbol *b = xb;
	if(!a->name) {
		if(!b->name) return 0;
		return 1;
	}
	if(!b->name) return -1;
	return strcmp(a->name, b->name);
}

void printrefs()
{
	struct symbol *sp;
	qsort(symtab, NHASH, sizeof(struct symbol), symcompare); /* sort the symbol table */
	for(sp = symtab; sp->name && sp < symtab+NHASH; sp++) {
		char *prevfn = NULL;
		/* last printed filename, to skip dups */
		/* reverse the list of references */
		struct ref *rp = sp->reflist;
		struct ref *rpp = 0;	/* previous ref */
		struct ref *rpn;	/* next ref */
		do {
			rpn = rp->next;
			rp->next = rpp;
			rpp = rp;
			rp = rpn;
		} while(rp);
		
		/* now print the word and its references */
		printf("%10s", sp->name);
		for(rp = rpp; rp; rp = rp->next) {
			if(rp->filename == prevfn) {
		printf(" %d", rp->lineno);
			} else {
		printf(" %s:%d", rp->filename, rp->lineno);
		prevfn = rp->filename;		
			}
			if(rp->flags & 01) printf("*");	
		}
		printf("\n");
	}

}

int main(argc, argv)
int argc;
char **argv;
{
	int i;
	if(argc < 2) {
		fprintf(stderr, "need filename\n");
		return 1;
	}
	for(i = 1; i < argc; i++) {
		if(newfile(argv[i]))
		yylex();
	}
	printrefs();
	return 0;
}

